### ISSUE TITLE
What does check-latest actually do?

### ISSUE THREAD

**Issue by dabrahams** [SwiftyLab/setup-swift#235]
The description “Whether to check with latest swift.org versions” doesn't really tell me what excactly it's checking or what it does with the information, and I tried to read the code to understand what the option means but couldn't figure it out.

**Comment by soumyamahunt** [comment]
Thanks @dabrahams for the feedback I will try to make the documentation clearer.

When I started building this action I wanted this to be as low of maintenance as possible. The way I achieved this is by parsing the content of the swift.org site for latest toolchains. This allows me not to manually add support for newly published toolchains as long as there is no breaking change.

The limitation with having this approach is as soon as a braking change introduced in swift.org toolchain format the action will break. Hence the final approach I want with is to by default use a specific snapshot of swift.org website that is tested exhaustively with the CI of this action. This snapshot is also updated daily after passing all the requirements. One example is [this PR](https://github.com/SwiftyLab/setup-swift/pull/237), since some of the tests are failing the merging is blocked.

`check-latest` allows you to circumvent this by taking the latest snapshot instead of using the pre-chosen snapshot. To give you one example, currently the swift.org snapshot this action uses has Swift 5.9.2 as the stable toolchain, with `check-latest` you can use the latest published Swift 5.10 in swift.org. But this comes at a cost of breaking your actions if there is a breaking change in swift.org.

**Comment by soumyamahunt** [comment]
You are welcome @dabrahams, I am not planning to add this in README since this is too much information that user's aren't concerned with. The condensed version will be added to `action.yml`

**Comment by soumyamahunt** [comment]
@dabrahams the `action.yml` is updated with more understandable wording and also [wiki](https://github.com/SwiftyLab/setup-swift/wiki/What-does-check%E2%80%90latest-actually-do%3F) is created with more detailed answer. Hence, closing this issue.
